version: '2.4'

x-es:
  &es
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
  ulimits:
    memlock:
      soft: -1
      hard: -1
  networks:
    - esnet
  volumes:
    - esdata:/usr/share/elasticsearch/data

services:
  astrosims-es:
    << : *es
    container_name: astrosims-es
    environment:
      - cluster.name=astrosims
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - "discovery.seed_hosts=astrosims-es"
      - "cluster.initial_master_nodes=astrosims-es"
      - "node.max_local_storage_nodes=8"
      - "node.name=astrosims-es"
    expose:
      - "9200"
    ports:
      - "127.0.0.1:9200:9200"
  es:
    << : *es
    environment:
      - cluster.name=astrosims
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
      - "discovery.seed_hosts=astrosims-es"
      - "cluster.initial_master_nodes=astrosims-es"
      - "node.max_local_storage_nodes=8"
    scale: 4
  astrosims:
    build: .
    image: flatironinstitute/astrosims-reproto
    networks:
      - esnet
    ports:
      - "80:8092"
    depends_on:
      - astrosims-es

volumes:
  esdata:

networks:
  esnet:
