apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrosims
spec:
  replicas: 2
  selector:
    matchLabels:
      name: astrosims
  template:
    metadata:
      labels:
        name: astrosims
    spec:
      initContainers:
      - name: wait-es
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - '-c'
          - until wget http://astrosims-es:9200/ ; do sleep 5 ; done
      containers:
      - image: flatironinstitute/astrosims-reproto:latest
        name: astrosims
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 16Gi
        ports:
        - containerPort: 8092
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
              - name: accept
                value: application/json
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: astrosims
spec:
  selector:
    name: astrosims
  ports:
  - name: http
    port: 80
    targetPort: http
  #externalIPs:
