apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrosims
spec:
  replicas: 2
  selector:
    matchLabels:
      name: astrosims
  template:
    metadata:
      labels:
        name: astrosims
    spec:
      imagePullSecrets:
      - name: docker-registry-auth
      initContainers:
      - name: wait-es
        image: busybox
        command:
          - sh
          - '-c'
          - until wget http://astrosims-es:9200/ ; do sleep 5 ; done
      containers:
      - image: gordon-dm4:25703/flatironinstitute/astrosims
        name: astrosims
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 16Gi
        ports:
        - containerPort: 8092
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
              - name: accept
                value: application/json
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 60
        volumeMounts:
          - mountPath: /home/astrosims/astrosims/tls
            name: tls
      volumes:
        - name: tls
          secret:
            secretName: astrosims-tls
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: astrosims
spec:
  selector:
    name: astrosims
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
  externalIPs:
  - 132.249.245.247
  - 132.249.246.13
