apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrosims
spec:
  selector:
    matchLabels:
      name: astrosims
  template:
    metadata:
      labels:
        name: astrosims
    spec:
      initContainers:
      - name: wait-es
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - '-c'
          - until wget http://astrosims-es:9200/ ; do sleep 5 ; done
      containers:
      - image: docker-registry:25703/flatironinstitute/astrosims
        name: astrosims
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 16Gi
        ports:
        - containerPort: 8092
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            httpHeaders:
              - name: accept
                value: application/json
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 60
        volumeMounts:
          - mountPath: /home/astrosims/astrosims/tls
            name: tls
      volumes:
        - name: tls
          secret:
            secretName: astrosims-tls
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: astrosims
spec:
  selector:
    name: astrosims
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
  type: LoadBalancer
  loadBalancerIP: 132.249.246.21
  externalTrafficPolicy: Local
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: astrosims
spec:
  rules:
  - host: astrosims.flatironinstitute.org
    http:
      paths:
      - path: /
        backend:
          serviceName: astrosims
          servicePort: 80
  - host: flathub.flatironinstitute.org
    http:
      paths:
      - path: /
        backend:
          serviceName: astrosims
          servicePort: 80
  tls:
    - hosts:
      - astrosims.flatironinstitute.org
      - flathub.flatironinstitute.org
      secretName: astrosims-tls
