resolver: lts-18.28
packages:
- '.'
extra-deps:
  - web-inv-route-0.1.3.1
  - git: https://github.com/dylex/waimwork
    commit: 0ec1caed3aaa4583430484b2b63b5793b94cdb61
  - git: https://github.com/dylex/hs-hdf5
    commit: 49c9a85136d14c551c9c533ff5f0410ef3feb498
  - bzlib-0.5.1.0
flags:
  web-inv-route:
    snap: false
    happstack: false
